site:
    name: "Neil Dandekar"
    title_suffix: "Neil Dandekar"
    notebook_label: "Thoughts"
    footer_credit: "Built by Neil"
    source_url: "https://github.com/neildandekar/neil-dandekar.github.io"
    socials:
        github: "https://github.com/neildandekar10"
        linkedin: "https://www.linkedin.com/in/neildandekar10/"
        instagram: "https://www.instagram.com/neildandekar/"
        x: "https://x.com/neildandekar10"

home:
    intro_title: "Hi, I'm Neil."
    intro_paragraphs:
        - "I'm a senior at UC San Diego studying data science. I'm excited by the future of embodied AI agents, robotics, and learning algorithms. I'm also an FC Barcelona fan, a food enjoyer, and ranked in Clash Royale."
        - ""
    experience_label: "Experience"
    experience_empty: "Experience updates soon."
    experiences:
        - role: "Software Engineering Intern"
          company: "Databricks"
          period: "Jun 2026 - Sep 2026"
          location: "Mountain View, CA"
          summary: "Incoming Summer 2026!"
          logo:
              src: "/assets/experience/databricks.png"
              alt: "Databricks logo"
        - role: "Software Engineering Intern"
          company: "Google"
          period: "Mar 2026 - Jun 2026"
          location: "Sunnyvale, CA"
          summary: "I'll be optimizing the scheduler for BorgGoogle's Technical Infrastructure soon, where I'll be optimizing the scheduler for Borg. If you're familiar with Kubernetes, Borg is its predecessor and Google's propietary container orchestration service."
          logo:
              src: "/assets/experience/google.png"
              alt: "Google logo"
        - role: "Software Development Engineer Intern"
          company: "Amazon"
          period: "Jun 2025 - Sep 2025"
          location: "Bellevue, WA"
          summary: "I owned, developed, and deployed an agentic platform to automate chaos engineering for Amazon Fulfillment Technology. I had a lot of fun experimenting with multi-agent orchestration and Model Context Protocol."
          logo:
              src: "/assets/experience/amazon.png"
              alt: "Amazon logo"
        - role: "Machine Learning Engineer Intern"
          company: "Berkeley Lab"
          period: "Jun 2024 - Aug 2024"
          location: "Berkeley, CA"
          summary: "I worked on ."
          logo:
              src: "/assets/experience/lbnl.png"
              alt: "Berkeley Lab logo"
        - role: "Software Engineer Intern"
          company: "Berkeley Lab"
          period: "Jan 2024 - Mar 2024"
          location: "Berkeley, CA"
          summary: "Worked on various fullstack features for a new portal"
          logo:
              src: "/assets/experience/lbnl.png"
              alt: "Berkeley Lab logo"

thoughts:
    heading: "Thoughts"
    sort_label: "Sort"
    sort_newest: "Newest first"
    sort_oldest: "Oldest first"
    empty_message: "No entries yet."
